<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/AppIcon.png" />
    <Content Include="Assets/AppIcon.icns" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="info/**/*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="mods/**/*" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="locales/*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
