import {rows} from './mod-engine.js';
export function download(name,content){const url=URL.createObjectURL(new Blob([content]));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export class SaveFile{
  constructor(buffer){this.original=new Uint8Array(buffer).slice();this.data=this.original.slice();if(this.data.length<0x4da3a0||String.fromCharCode(...this.data.slice(4,8))!=='UCSD')throw Error('不支持或不完整的 UCSD 存档');this.view=new DataView(this.data.buffer);}
  read(address,size=4){this.check(address,size);let value=0;for(let index=size-1;index>=0;index--)value=value*256+this.data[address+index];return value;}
  check(address,size){if(!Number.isInteger(address)||address<0||address+size>this.data.length)throw Error('存档地址越界');}
  write(address,size,value){this.check(address,size);if(!Number.isInteger(value)||value<0||value>=2**(size*8))throw Error(`数值必须为 0–${2**(size*8)-1} 的整数`);for(let index=0;index<size;index++){this.data[address+index]=value%256;value=Math.floor(value/256);}}
  characters(){const result=[];for(let index=0;index<500;index++){const address=0x2af40+index*464;if(this.read(address)===0xffffffff)break;result.push(address);}return result;}
  inventory(){const result=[];for(let index=0;index<3800;index++){const address=0xa0+index*20;if(this.read(address+4)===0)break;result.push(address);}return result;}
  bonds(character){const id=this.read(character);for(let index=0;index<164;index++){const base=0x1b5830+index*1316;if(this.read(base)===0xffffffff)break;if(this.read(base)!==id)continue;const result=[];for(let slot=0;slot<164;slot++){const address=base+4+slot*8;if(this.read(address)===0xffffffff)break;result.push(address);}return result;}return [];}
  addItems(ids,equipment,kinds){const inventory=this.inventory();if(inventory.length+ids.length>3800)throw Error('库存容量不足，未写入');ids.forEach((id,index)=>{const address=0xa0+(inventory.length+index)*20;this.data.fill(0,address,address+20);this.write(address,4,id);this.write(address+4,4,inventory.length+index+1);this.write(address+8,3,equipment?0:1);this.write(address+16,4,Number(kinds.get(id)?.[1]||2));});}
  importCharacter(buffer,address){const data=new Uint8Array(buffer).slice();if(data.length!==464)throw Error('角色文件必须恰为 464 字节');const existing=this.characters();if(address===undefined&&existing.length>=500)throw Error('角色已满');const adding=address===undefined;address??=0x2af40+existing.length*464;const id=adding?this.read(0x63980)+1:this.read(address);if(id>=0xffffffff)throw Error('角色 ID 耗尽');new DataView(data.buffer).setUint32(0,id,true);data.fill(255,4,8);data[32]=255;data[460]&=254;data.fill(0,76,92);this.data.set(data,address);
    if(adding){this.write(0x63980,4,id);this.write(0x63984,4,this.read(0x63984)+1);for(let index=0;index<164;index++){const base=0x1b5830+index*1316;if(this.read(base)===0xffffffff){this.write(base,4,id);existing.slice(0,164).forEach((other,slot)=>{this.write(base+4+slot*8,4,this.read(other));this.write(base+8+slot*8,4,0);});break;}for(let slot=0;slot<164;slot++)if(this.read(base+4+slot*8)===0xffffffff){this.write(base+4+slot*8,4,id);this.write(base+8+slot*8,4,0);break;}}}
    return address;
  }
}
export function mountSave(container,catalog,notify){
  container.className='save-editor';let save,filename='',section='基本',selectedCharacter=0;const tables=Object.fromEntries(['class','name','item','kind'].map(name=>[name,new Map(rows(catalog.info[name+'.txt']).map(row=>[Number(row[0]),row]))]));const name=(table,id)=>{const row=tables[table].get(id);return row?.[3]||row?.[2]||row?.[1]||`ID ${id}`;};
  const element=(tag,text,parent)=>{const result=document.createElement(tag);if(text!==undefined)result.textContent=text;parent?.append(result);return result;};
  const action=(parent,text,callback)=>{const button=element('button',text,parent);button.onclick=async()=>{try{await callback();notify('操作完成；源文件未覆盖，请下载修改后的存档。');}catch(error){notify(error.message,true);}};return button;};
  const filePicker=async(accept,callback)=>{const input=document.createElement('input');input.type='file';input.accept=accept;input.onchange=async()=>{try{if(input.files[0])await callback(input.files[0]);}catch(error){notify(error.message,true);}};input.click();};
  function number(parent,label,address,size,min=0,max=2**(size*8)-1){const wrapper=element('label',label,parent);wrapper.className='field';const input=element('input',undefined,wrapper);input.type='number';input.min=min;input.max=max;input.value=save.read(address,size);input.onchange=()=>{try{const value=Number(input.value);if(input.value===''||value<min||value>max)throw Error(`${label}范围为${min}–${max}`);save.write(address,size,value);}catch(error){notify(error.message,true);input.value=save.read(address,size);}};return input;}
  function select(parent,label,table,address,size){const wrapper=element('label',label,parent);wrapper.className='field';const input=element('select',undefined,wrapper);input.setAttribute('aria-label',label);for(const [id] of tables[table]){const option=element('option',`${id} · ${name(table,id)}`,input);option.value=id;}input.value=save.read(address,size);input.onchange=()=>save.write(address,size,Number(input.value));return input;}
  function render(){container.replaceChildren();const card=element('div',undefined,container);card.className='card';const top=element('div',undefined,card);top.className='card-head';const title=element('div',undefined,top);element('h2','存档编辑',title);element('p',save?filename+' · 修改只存在当前页面内存':'选择 UCSD 格式 .DAT 文件，在本地修改并下载副本。',title);const controls=element('div',undefined,top);controls.className='actions';action(controls,'打开存档',()=>filePicker('.dat,.DAT',async file=>{if(save&&!confirm('打开新存档将丢弃当前未下载的修改，继续？'))return;if(file.size>64*1024*1024)throw Error('存档超过 64 MiB');const candidate=new SaveFile(await file.arrayBuffer());save=candidate;filename=file.name;selectedCharacter=0;render();}));if(!save){element('p','原始文件不会被覆盖。支持角色、亲密度、道具、装备和部队。请务必先下载原始备份。',card);return;}
    action(controls,'下载原始备份',()=>download('backup_'+filename,save.original));action(controls,'下载修改后存档',()=>download(filename,save.data)).className='primary';const tabs=element('div',undefined,card);tabs.className='tabs';for(const label of ['基本','角色','道具','装备','部队'])action(tabs,label,()=>{section=label;render();}).className=section===label?'active':'';const body=element('div',undefined,card);
    if(section==='基本'){body.className='grid';number(body,'金币',0x20,4);number(body,'声望',0x24,4);const label=element('label','解锁 ZENOIRA 难度',body);label.className='toggle';const check=element('input',undefined,label);check.type='checkbox';check.checked=save.read(0x4da39e,2)===0x4040;check.onchange=()=>save.write(0x4da39e,2,check.checked?0x4040:0);}
    if(section==='角色'){
      const characters=save.characters(),picker=element('select',undefined,body);picker.setAttribute('aria-label','选择存档角色');characters.forEach((address,index)=>{const option=element('option',`${index+1} · ${name('name',save.read(address+52,2))} · ${name('class',save.read(address+40,1))}`,picker);option.value=index;});picker.value=Math.min(selectedCharacter,characters.length-1);picker.onchange=()=>{selectedCharacter=Number(picker.value);render();};const address=characters[Number(picker.value)],actions=element('div',undefined,body);actions.className='actions section-label';
      action(actions,'从文件新增角色',()=>filePicker('.uocd',async file=>{save.importCharacter(await file.arrayBuffer());render();}));if(address===undefined)return;
      action(actions,'导出当前角色',()=>download('角色.uocd',save.data.slice(address,address+464)));action(actions,'用文件替换角色',()=>filePicker('.uocd',async file=>{if(!confirm('替换当前角色并清除其装备和编队引用？'))return;save.importCharacter(await file.arrayBuffer(),address);render();}));const grid=element('div',undefined,body);grid.className='grid three';select(grid,'职业','class',address+40,1);number(grid,'等级',address+60,2,1,99);number(grid,'经验',address+56,4);['生命','物攻','物防','魔攻','魔防','命中','闪避','暴击','格挡','速度'].forEach((label,index)=>number(grid,label+'加成',address+64+index,1));const useLabel=element('label','可使用',grid);useLabel.className='toggle';const use=element('input',undefined,useLabel);use.type='checkbox';use.checked=!(save.read(address+460,1)&32);use.onchange=()=>save.write(address+460,1,use.checked?save.read(address+460,1)&223:save.read(address+460,1)|32);
      const bonds=save.bonds(address);element('h3','亲密度',body).className='section-label';action(body,'当前角色亲密度全部设为1000',()=>{for(const bond of bonds)save.write(bond+4,4,1000);render();});const bondGrid=element('div',undefined,body);bondGrid.className='grid three';for(const bond of bonds){const target=characters.find(other=>save.read(other)===save.read(bond));number(bondGrid,target?name('name',save.read(target+52,2)):`角色 ID ${save.read(bond)}`,bond+4,4,0,1000);}
    }
    if(section==='道具'||section==='装备'){
      const equipment=section==='装备',inventory=save.inventory(),entries=inventory.filter(address=>(save.read(address+8,3)===0)===equipment);element('p',`库存记录 ${inventory.length} / 3800 · 当前分类 ${entries.length} 条。装备数量为0是原版记录结构，请勿改为道具数量。`,body);const controls=element('div',undefined,body);controls.className='actions';const picker=element('select',undefined,controls);picker.style.maxWidth='320px';picker.setAttribute('aria-label','添加物品');for(const [id] of tables.item)if(id>0&&(tables.kind.has(id)===equipment)){const option=element('option',`${id} · ${name('item',id)}`,picker);option.value=id;}action(controls,'添加所选',()=>{save.addItems([Number(picker.value)],equipment,tables.kind);render();});action(controls,equipment?'补齐缺少的装备':'补齐安全消耗道具',()=>{const existing=new Set(entries.map(address=>save.read(address)));const ids=[...tables.item.keys()].filter(id=>!existing.has(id)&&(equipment?tables.kind.has(id):id>=8&&id<=69||id===71||id>=73&&id<=171));save.addItems(ids,equipment,tables.kind);render();});if(!equipment)action(controls,'道具数量批量设置',()=>{const raw=prompt('设置数量（1–999；保护 ID 0–4）','99');if(raw===null)return;const count=Number(raw);if(!Number.isInteger(count)||count<1||count>999)throw Error('数量范围1–999');for(const address of entries)if(save.read(address)>4)save.write(address+8,3,count);render();});const search=element('input',undefined,body);search.placeholder='搜索物品名称 / ID';search.style.margin='18px 0';const list=element('div',undefined,body);list.className='table-scroll';const show=()=>{list.replaceChildren();const table=element('table',undefined,list);for(const address of entries){const id=save.read(address);if(!`${id} ${name('item',id)}`.toLowerCase().includes(search.value.toLowerCase()))continue;const row=element('tr',undefined,table);element('td',`${id} · ${name('item',id)}`,row);const cell=element('td',undefined,row);if(equipment)element('span',`装备引用：${save.read(address+11,1)} / ${save.read(address+12,1)}`,cell);else number(cell,'数量',address+8,3,1,999);}};search.oninput=show;show();
    }
    if(section==='道具'||section==='装备'){
      const equipment=section==='装备',entries=save.inventory().filter(address=>(save.read(address+8,3)===0)===equipment);
      const details=element('details',undefined,body);element('summary','替换库存中的道具 / 装备',details);const grid=element('div',undefined,details);grid.className='grid';
      const current=element('select',undefined,grid);current.setAttribute('aria-label','待替换的库存记录');for(const address of entries){const option=element('option',`${save.read(address+4)} · ${name('item',save.read(address))}`,current);option.value=address;}
      const replacement=element('select',undefined,grid);replacement.setAttribute('aria-label','替换为');for(const [id] of tables.item)if(id>0&&tables.kind.has(id)===equipment){const option=element('option',`${id} · ${name('item',id)}`,replacement);option.value=id;}
      action(details,'替换所选记录',()=>{if(!current.value||!replacement.value)throw Error('请选择库存记录与替换物品');const address=Number(current.value),id=Number(replacement.value);save.write(address,4,id);save.write(address+16,4,equipment?Number(tables.kind.get(id)[1]):2);render();});
    }
    if(section==='部队'){body.className='grid';for(let index=0;index<10;index++){const address=0x10d89a+index*1720,card=element('div',undefined,body);card.className='card';element('h3',`部队 ${index+1}`,card);number(card,'人数上限',address,1,1,6);const label=element('label','启用部队',card);label.className='toggle';const input=element('input',undefined,label);input.type='checkbox';input.checked=save.read(address+1670,1)===1;input.onchange=()=>save.write(address+1670,1,input.checked?1:0);}}
  }
  render();return {hasChanges:()=>save&&!save.data.every((byte,index)=>byte===save.original[index])};
}
